name: Release Please Charts

on:
  push:
    branches: [master]
  # Allow to run the workflow from GitHub UI and other workflows.
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release-please-action
        uses: google-github-actions/release-please-action@v4.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: helm
